"""upgd_caracterizacion

Revision ID: 024c8692085a
Revises: 6fce7513b565
Create Date: 2026-09-25 00:28:03.771029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024c8692085a'
down_revision: Union[str, Sequence[str], None] = '6fce7513b565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upgd_caracterizacion',
    sa.Column('cod_prestador', sa.String(length=12), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('nivel_complejidad', sa.Integer(), nullable=False),
    sa.Column('cove', sa.Boolean(), nullable=False),
    sa.Column('unidad_analisis', sa.Boolean(), nullable=False),
    sa.Column('internet', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('departamento_codigo', sa.String(length=2), nullable=True),
    sa.Column('municipio_codigo', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['departamento_codigo'], ['departamentos.codigo'], ),
    sa.ForeignKeyConstraint(['municipio_codigo'], ['municipios.codigo'], ),
    sa.PrimaryKeyConstraint('cod_prestador')
    )
    op.create_foreign_key('fk_usuarios_cod_upgd_upgd_caracterizacion', 'usuarios', 'upgd_caracterizacion', ['cod_upgd'], ['cod_prestador'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuarios_cod_upgd_upgd_caracterizacion', 'usuarios', type_='foreignkey')
    op.drop_table('upgd_caracterizacion')
    # ### end Alembic commands ###
