"""modulo_docente

Revision ID: 14371d7d9097
Revises: a67a6cf60073
Create Date: 2026-09-25 00:55:47.085416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14371d7d9097'
down_revision: Union[str, Sequence[str], None] = 'a67a6cf60073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escenarios_clinicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=False),
    sa.Column('cod_evento', sa.String(length=10), nullable=False),
    sa.Column('datos_esperados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name='fk_escenarios_clinicos_creado_por'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escenarios_clinicos_cod_evento'), 'escenarios_clinicos', ['cod_evento'], unique=False)
    op.create_table('escenario_asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escenario_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ASIGNADO', 'EN_PROGRESO', 'COMPLETADO', name='estado_asignacion'), server_default='ASIGNADO', nullable=False),
    sa.Column('ficha_basica_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escenario_id'], ['escenarios_clinicos.id'], name='fk_escenario_asignaciones_escenario'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuarios.id'], name='fk_escenario_asignaciones_estudiante'),
    sa.ForeignKeyConstraint(['ficha_basica_id'], ['fichas_datos_basicos.id'], name='fk_escenario_asignaciones_ficha_basica'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escenario_asignaciones_escenario_id'), 'escenario_asignaciones', ['escenario_id'], unique=False)
    op.create_index(op.f('ix_escenario_asignaciones_estudiante_id'), 'escenario_asignaciones', ['estudiante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escenario_asignaciones_estudiante_id'), table_name='escenario_asignaciones')
    op.drop_index(op.f('ix_escenario_asignaciones_escenario_id'), table_name='escenario_asignaciones')
    op.drop_table('escenario_asignaciones')
    op.drop_index(op.f('ix_escenarios_clinicos_cod_evento'), table_name='escenarios_clinicos')
    op.drop_table('escenarios_clinicos')
    # ### end Alembic commands ###
