"""ficha_datos_basicos

Revision ID: 45be635431fb
Revises: 024c8692085a
Create Date: 2026-09-25 00:35:49.803529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45be635431fb'
down_revision: Union[str, Sequence[str], None] = '024c8692085a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fichas_datos_basicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_upgd', sa.String(length=20), nullable=False),
    sa.Column('subindice', sa.String(length=5), nullable=False),
    sa.Column('cod_evento', sa.String(length=10), nullable=False),
    sa.Column('f_grabacion', sa.Date(), nullable=False),
    sa.Column('f_notificacion', sa.Date(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('semana_epidemiologica', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.String(length=5), nullable=False),
    sa.Column('num_id', sa.String(length=20), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('f_nacimiento', sa.Date(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('und_med_edad', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('identidad_genero', sa.Integer(), nullable=False),
    sa.Column('orientacion_sexual', sa.Integer(), nullable=False),
    sa.Column('pais_ocurrencia', sa.String(length=50), nullable=False),
    sa.Column('dpto_ocurrencia', sa.String(length=5), nullable=False),
    sa.Column('muni_ocurrencia', sa.String(length=5), nullable=False),
    sa.Column('area_ocurrencia', sa.Integer(), nullable=False),
    sa.Column('grupos_poblacionales', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clasificacion_caso', sa.Integer(), nullable=False),
    sa.Column('hospitalizado', sa.Boolean(), nullable=False),
    sa.Column('condicion_final', sa.Integer(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], name='fk_fichas_basicas_creado_por_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fichas_datos_basicos_cod_evento'), 'fichas_datos_basicos', ['cod_evento'], unique=False)
    op.create_index(op.f('ix_fichas_datos_basicos_cod_upgd'), 'fichas_datos_basicos', ['cod_upgd'], unique=False)
    op.create_index(op.f('ix_fichas_datos_basicos_num_id'), 'fichas_datos_basicos', ['num_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fichas_datos_basicos_num_id'), table_name='fichas_datos_basicos')
    op.drop_index(op.f('ix_fichas_datos_basicos_cod_upgd'), table_name='fichas_datos_basicos')
    op.drop_index(op.f('ix_fichas_datos_basicos_cod_evento'), table_name='fichas_datos_basicos')
    op.drop_table('fichas_datos_basicos')
    # ### end Alembic commands ###
