"""ficha_datos_complementarios

Revision ID: 5210c2ca17b8
Revises: 45be635431fb
Create Date: 2026-09-25 00:42:12.051434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5210c2ca17b8'
down_revision: Union[str, Sequence[str], None] = '45be635431fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fichas_datos_complementarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_basica_id', sa.Integer(), nullable=False),
    sa.Column('cod_evento', sa.String(length=10), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['ficha_basica_id'], ['fichas_datos_basicos.id'], name='fk_fichas_complementarias_ficha_basica'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ficha_basica_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fichas_datos_complementarios')
    # ### end Alembic commands ###
