"""add usuarios table

Revision ID: 6c9a66ee4d82
Revises: 46739a8b908c
Create Date: 2026-09-25 00:11:44.082903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9a66ee4d82'
down_revision: Union[str, Sequence[str], None] = '46739a8b908c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('UPGD', 'UI', 'MUNICIPAL', 'DEPARTAMENTAL', 'NACIONAL', 'DOCENTE', name='rol_enum'), nullable=False),
    sa.Column('cod_upgd', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cod_upgd'), 'usuarios', ['cod_upgd'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cod_upgd'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
