"""catalogos

Revision ID: 6fce7513b565
Revises: 6c9a66ee4d82
Create Date: 2026-09-25 00:20:20.465155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fce7513b565'
down_revision: Union[str, Sequence[str], None] = '6c9a66ee4d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('etnias',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('eventos',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ocupaciones',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('municipios',
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('departamento_codigo', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['departamento_codigo'], ['departamentos.codigo'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_municipios_departamento_codigo'), 'municipios', ['departamento_codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_departamento_codigo'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_table('ocupaciones')
    op.drop_table('eventos')
    op.drop_table('etnias')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
