"""usuarios_numero_identificacion

Revision ID: 7e0bf827495d
Revises: 14371d7d9097
Create Date: 2026-09-25 09:41:08.878764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0bf827495d'
down_revision: Union[str, Sequence[str], None] = '14371d7d9097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('numero_identificacion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'numero_identificacion')
    # ### end Alembic commands ###
